#!/bin/bash

# put back any of the quotes that BASH removed
# so we can show the user what we're running underneath
execute_and_echo() {
    args=''
    whitespace="[[:space:]]"
    for i in "$@"
    do
        if [[ $i =~ $whitespace ]]
        then
            i=\"$i\"
        fi
        args+="$i ";
    done
    echo "\$ $args"
    bash -c "$args"
}

# add sudo if we need to - and pass all arguments to the target
if [[ $EUID -ne 0 ]]; then
    execute_and_echo sudo python ./touch-mp3-lights.py "$@"
else
    execute_and_echo python ./touch-mp3-lights.py "$@"
fi
